// ============================================================
// USMA — Government Integration Layer
// integration_provider.dart
//
// STATUS: MOCK / DEMONSTRATION ARCHITECTURE
//
// This file defines the abstract contract (IntegrationProvider)
// that every integration adapter must implement.
//
// REAL IMPLEMENTATION: Domain models, retry logic, audit log.
// MOCK / DEMO:         All concrete providers below return
//                      deterministic simulated responses.
// FUTURE INTEGRATION:  When production credentials are
//                      provisioned, swap each mock class with
//                      a real HTTP adapter while keeping this
//                      interface unchanged.
// ============================================================


// ─────────────────────────────────────────────────────────────
// Response status
// ─────────────────────────────────────────────────────────────
enum IntegrationStatus {
  verified,
  mismatch,
  manualReview,
  pending,
  failed,
  sourceUnavailable,
}

// ─────────────────────────────────────────────────────────────
// System identifier (never claim live unless actually live)
// ─────────────────────────────────────────────────────────────
enum GovernmentSystem {
  digiLocker,
  udisePlus,
  apaar,
  aishe,
  nsp,
  pfms,
  stateEDistrict,
  ugc,
  nta,
}

extension GovernmentSystemLabel on GovernmentSystem {
  String get displayName {
    switch (this) {
      case GovernmentSystem.digiLocker:
        return 'DigiLocker';
      case GovernmentSystem.udisePlus:
        return 'UDISE+';
      case GovernmentSystem.apaar:
        return 'APAAR / ABC';
      case GovernmentSystem.aishe:
        return 'AISHE';
      case GovernmentSystem.nsp:
        return 'NSP';
      case GovernmentSystem.pfms:
        return 'PFMS / DBT';
      case GovernmentSystem.stateEDistrict:
        return 'State e-District';
      case GovernmentSystem.ugc:
        return 'UGC';
      case GovernmentSystem.nta:
        return 'NTA';
    }
  }

  /// Always append "(Mock)" so the UI never misleads the user.
  String get demoLabel => '${displayName} (Demo)';
}

// ─────────────────────────────────────────────────────────────
// Standardised request
// ─────────────────────────────────────────────────────────────
class IntegrationRequest {
  /// Opaque unique ID generated by the orchestrator per verification run.
  final String requestId;

  /// Masked/synthetic student ID — never expose real Aadhaar.
  final String studentId;

  /// Fields the orchestrator wants the provider to validate.
  final Map<String, String> fieldsToVerify;

  /// ISO-8601 timestamp the request was created.
  final DateTime createdAt;

  const IntegrationRequest({
    required this.requestId,
    required this.studentId,
    required this.fieldsToVerify,
    required this.createdAt,
  });
}

// ─────────────────────────────────────────────────────────────
// Standardised response
// ─────────────────────────────────────────────────────────────
class IntegrationResponse {
  final GovernmentSystem sourceSystem;
  final String requestId;
  final IntegrationStatus status;

  /// Fields that matched the declared values.
  final List<String> verifiedFields;

  /// Fields that differed between the application and the source.
  /// Key = fieldName, Value = sourceValue
  final Map<String, String> mismatchedFields;

  /// ISO-8601 timestamp of the response.
  final DateTime timestamp;

  /// Human-readable error detail (no PII in this field).
  final String? error;

  final bool requiresManualReview;

  /// Always true for mock providers. Must be false for live adapters.
  final bool isSimulated;

  const IntegrationResponse({
    required this.sourceSystem,
    required this.requestId,
    required this.status,
    this.verifiedFields = const [],
    this.mismatchedFields = const {},
    required this.timestamp,
    this.error,
    this.requiresManualReview = false,
    this.isSimulated = true,
  });
}

// ─────────────────────────────────────────────────────────────
// Abstract interface every provider must implement
// ─────────────────────────────────────────────────────────────
abstract class IntegrationProvider {
  /// The government system this provider represents.
  GovernmentSystem get system;

  /// Whether this adapter is a mock (demo mode) or live.
  bool get isSimulated;

  /// Maximum time to wait before treating the source as unavailable.
  Duration get timeout;

  /// Verify the fields in [request] and return a standardised response.
  Future<IntegrationResponse> verify(IntegrationRequest request);
}
